**PRÁCTICA CON ARRAYS EN NUMPY**

In [2]:
#importamos la librería
import numpy as np



1. Generar un array aleatorio de 100 elementos. Calcular la mediana correspondiente.

In [4]:
#Generamos un array aleatorio de 100 elementos
mi_array = np.random.randint(90,size=100)

print("Mi array es:\n\n",mi_array)

#Verificamos la cantidad de elementos del array
print(f"\nEste array tiene {np.size(mi_array)} elementos\n")

#Obtenemos la mediana del array
print("La mediana de mi array es: ",np.median(mi_array))

Mi array es:

 [22 46 81 44  0 25 28 51 70  1 49 88 45 12 79 20  2 73 25 82 16 59 30 37
 27 78 59 65 45 51 16 25  7 76 17 19 56 31 50 69 81 31 60 65 33 75 12 74
 57 43 74 87 69 43 83 48 77 30  7 81 73 44 77 62 29 51 73 47 46 24 77 64
 63 66 39 68 23 23  5 37 62 56 17 58 20 18 79 66 80 36 47 44 54 65 89 27
 54 59 27 53]

Este array tiene 100 elementos

La mediana de mi array es:  49.5




2. Generar un array que contenga siempre valor 1 en sus elementos y que tenga 20 elementos, luego otro array de rango 1 hasta el 20 inclusive. Sumarlos y luego decirme cual es el promedio del array resultante.



In [ ]:
#Generamos los dos arrays

## Array con 20 elementos igual a 1
mi_array_2 = np.ones(20,dtype=int)
## Array con un rango de 1 a 20
mi_array_3 = np.arange(1,21)

print("Array 1:\t",mi_array_2,"\n","\nArray 2:\t",mi_array_3)

#Sumamos ambos arrays
mi_array_4 = mi_array_2 + mi_array_3

print("\nSuma de Arrays:\t",mi_array_4)

#Calculamos su media
print("\nEl promedio de la suma de arrays es:\t",mi_array_4.mean())

Array 1:	 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 
 
Array 2:	 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Suma de Arrays:	 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

El promedio de la suma de arrays es:	 11.5


3. En base al array del ajedrez generado en esta diapositivas , hacer un cambio de forma(reshape) y que sea de 4 filas y 16 columnas. Calcular su desvio estandar.

In [ ]:
#Generamos el array del ajedrez

ajedrez_64 = np.arange(1,65).reshape(8,8)

print("Array del ajedrez:\n\n",ajedrez_64)

#Realizamos un reshape para que tenga 4 filas y 16 columnas

ajedrez_reshape = ajedrez_64.reshape(4,16)

print("\nArray del ajedrez con reshape:\n\n",ajedrez_reshape)

# Calculamos el desvío estándar del array

print("\nEl desvío estándar del array del ajedrez con reshape es: ",np.std(ajedrez_reshape))

Array del ajedrez:

 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

Array del ajedrez con reshape:

 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]]

El desvío estándar del array del ajedrez con reshape es:  18.472953201911167
